# Generated by Django 5.1.5 on 2025-04-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('made_at', models.IntegerField()),
                ('milage', models.IntegerField()),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('very good', 'Very good'), ('good', 'Good'), ('smaller investments required', 'Smaller investments required'), ('not working', 'Not working')], default='new', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='motorimages/')),
            ],
        ),
    ]
