# Generated by Django 5.1.5 on 2025-04-11 13:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_motor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motor',
            options={'ordering': ['brand', 'model'], 'verbose_name': 'Motor', 'verbose_name_plural': 'Motors'},
        ),
        migrations.AlterField(
            model_name='motor',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('very good', 'Very good'), ('good', 'Good'), ('smaller investments required', 'Smaller investments required'), ('not working', 'Not working')], default='new', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='made_at',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='motor',
            name='milage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='motor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='app.motor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['-created_at'],
            },
        ),
    ]
