# Generated by Django 5.1.5 on 2025-04-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_motor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motor',
            old_name='milage',
            new_name='mileage',
        ),
    ]
