# Generated by Django 5.2 on 2025-06-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_favoriteadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_ads',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.advertisement'),
        ),
        migrations.DeleteModel(
            name='FavoriteAdvertisement',
        ),
    ]
