# Generated by Django 5.2 on 2025-07-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_favorite_ads_delete_favoriteadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='power',
            field=models.PositiveIntegerField(blank=True, help_text='Power in HP (horsepower)', null=True),
        ),
    ]
