# Generated by Django 5.2 on 2025-07-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_motor_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/images/default.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='motor',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
