# Generated by Django 5.2 on 2025-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customuser_profile_image_alter_motor_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
